# Generated by Django 4.2.6 on 2023-12-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='dealt_with',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
