# Generated by Django 4.2.6 on 2023-12-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_feedback_dealt_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsageExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('associated_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.word')),
            ],
        ),
    ]
