# Generated by Django 4.2.6 on 2023-12-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_word_usageexample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsageExample',
            new_name='WordUsageExample',
        ),
    ]
