# Generated by Django 4.2.6 on 2023-12-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_usageexample_wordusageexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Acheivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points_required', models.IntegerField(null=True)),
                ('associated_trivia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.trivia')),
            ],
        ),
    ]
