# Generated by Django 4.2.6 on 2023-12-29 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_trivia_acheivement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acheivement',
            name='associated_trivia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.trivia'),
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer_a', models.CharField(max_length=255)),
                ('answer_b', models.CharField(max_length=255)),
                ('answer_c', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('worth_in_points', models.IntegerField()),
                ('associated_trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.trivia')),
            ],
        ),
    ]
