# Generated by Django 4.2.6 on 2024-01-04 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_alter_acheivement_associated_trivia_triviaquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='updated',
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('associated_trivia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.trivia')),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcheivementsUnlocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_acheivement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.acheivement')),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
